
MONGODB_URI = "mongodb://localhost:27017/courierOrganizer"

BEST_SPOTS_NUMBER = 10
GOOD_SPOTS_NUMBER = 5
RANDOM_SPOTS_NUMBER = 3
POPULATION_NUMBER = BEST_SPOTS_NUMBER + GOOD_SPOTS_NUMBER + RANDOM_SPOTS_NUMBER

BEST_SPOT_BEES = 10
GOOD_SPOT_BEES = 5

MAX_ITERATIONS_NUMBER = 10000
